# Domain settings
flippa_domain: DailyViva.com
flippa_domain_url: https://flippa.com/5925939-no-title
flippa_buy_now_price: 549

# Portfolio settings
flippa_portfolio_url: https://flippa.com/domain-catalogs/38205
flippa_portfolio_domains:
  - name: kyn.me
  - url: http://flippa.com/5910172

# Build settings
markdown: kramdown
